# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-longhorn-hotfix
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: hotfix/longhorn-v1.11.0-hotfix-1
  url: https://github.com/coredev-uk/homelab
